<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.SpiceTG.TestCases.LoginPagesTestCase" tests="1" time="10.460" ignored="3" failures="0" timestamp="22 Oct 2019 13:30:12 GMT" skipped="0" hostname="leomahesh-PC" errors="1">
  <testcase name="SpiceValidLoginTest" time="10.460" classname="com.SpiceTG.TestCases.LoginPagesTestCase">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy8.sendKeys(Unknown Source)
	at com.SpiceTG.pages.SpiceTG_LoginPage.validateUserNamePWD(SpiceTG_LoginPage.java:80)
	at com.SpiceTG.TestCases.LoginPagesTestCase.SpiceValidLoginTest(LoginPagesTestCase.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- SpiceValidLoginTest -->
  <testcase name="SpicePageTitleTest" classname="com.SpiceTG.TestCases.LoginPagesTestCase">
    <skipped/>
  </testcase> <!-- SpicePageTitleTest -->
  <testcase name="SpiceLogoTest" classname="com.SpiceTG.TestCases.LoginPagesTestCase">
    <skipped/>
  </testcase> <!-- SpiceLogoTest -->
  <testcase name="Test4" classname="com.SpiceTG.TestCases.LoginPagesTestCase">
    <skipped/>
  </testcase> <!-- Test4 -->
</testsuite> <!-- com.SpiceTG.TestCases.LoginPagesTestCase -->
